---

# /etc/hosts for now
- name: set /etc/hosts master0
  lineinfile:
    dest: /etc/hosts
    line: "{{ master0PublicIP }} {{ azure.virtualMachineMaster }}.westeurope.cloudapp.azure.com"
    state: present
  become: true
  become_user: root
  become_method: sudo

- name: set hostname
  hostname:
    name: "{{ azure.virtualMachineMaster }}.westeurope.cloudapp.azure.com"
  become: true
  become_user: root
  become_method: sudo

...
