---

- name: Restart docker
  systemd:
    name: docker
    state: restarted
  become: true
  become_user: root
  become_method: sudo

- name: Restart openshift
  systemd:
    name: openshift
    state: restarted
    enabled: yes
  become: true
  become_user: root
  become_method: sudo

...
